table Results
	lineageTag: ffa596c6-aec4-4c63-912a-804618788065

	measure Actual_Status = ```
			
			VAR varLatestDateWithValue = 
			    CALCULATE(
			        MAX('results'[Date]),
			        'results'[Actual_Value] <> 0
			    )
			VAR varLatestValue = 
			    CALCULATE(
			        SUM('results'[Actual_Value]),
			        'results'[Date] = varLatestDateWithValue
			    )
			
			RETURN
			    varLatestValue
			```
		lineageTag: f92170d1-51f9-4454-9966-172af2ec516a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Calculated_Target_Value = ```
			
			// 1. Identify the unit for the current KPI context
			VAR _UnitName = SELECTEDVALUE(units[Unit_Name])
			
			// 2. Get the raw target value from the KPIs table
			VAR _Target = SELECTEDVALUE(kpis[Target_Value])
			
			// 3. Retrieve the Actual_Value that serves as the baseline (Beginning Number)
			// We use CALCULATE to filter the Results table specifically for the starting point
			VAR _StartingActual = 
			    CALCULATE(
			        MAX(Results[Actual_Value]), 
			        Results[Is_Beginning_Number] = TRUE
			    )
			
			// 4. Final Logic:
			// If Unit is "Percentage", add the Target to the Starting Value.
			// Otherwise, simply return the Target Value.
			RETURN
			IF(
			    _UnitName = "Percentage",
			    _StartingActual + _Target,
			    _Target
			)
			```
		formatString: 0
		lineageTag: a33060ba-5c27-4763-ade5-38bcc11a29f0

	measure Compliance_Percentage = ```
			
			-- 1. Safely divide the Actual Status by the Planned target
			-- Using DIVIDE() automatically handles divide-by-zero scenarios by returning BLANK
			VAR varCompliance = 
			    DIVIDE(
			        [Actual_Status], 
			        [Adjusted_Target_Value],
			        BLANK()
			    )
			
			-- 2. Return the decimal value (to be formatted as 0.00% in the UI)
			RETURN
			    varCompliance
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1605eb15-a5e4-4751-a3a1-9554ebe2d367

	measure Objective_Completion_Rate = ```
			
			-- 1. Iterate over the 'kpis' dimension table in the current filter context
			-- AVERAGEX will automatically handle the denominator (e.g., dividing by 3 if there are 3 KPIs)
			VAR varAverageCompletion = 
			    AVERAGEX(
			        'kpis',
			        
			        -- 2. Retrieve the raw compliance percentage for each individual KPI
			        -- COALESCE ensures that if a KPI has no data yet, it counts as 0% rather than being ignored
			        VAR varRawCompliance = COALESCE([Compliance_Percentage], 0)
			        
			        -- 3. Cap the compliance at 100% (1.0)
			        -- MIN is the most efficient way to cap values in DAX (avoids IF statements)
			        VAR varCappedCompliance = MIN(varRawCompliance, 1)
			        
			        -- 4. Return the capped value to the AVERAGEX iteration loop
			        RETURN
			            varCappedCompliance
			    )
			
			-- 5. Return the final aggregated average (Format this measure as 0.00% in the UI)
			RETURN
			    varAverageCompletion
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6c9efaab-b75d-46e2-b42a-52c4e6039e73

	measure Compliance_Actual_Value_Percentage = ```
			
			-- 1. Safely divide the Actual Status by the Planned target
			-- Using DIVIDE() automatically handles divide-by-zero scenarios by returning BLANK
			VAR varCompliance = 
			    DIVIDE(
			        [Total_Actual_Value], 
			        [Adjusted_Target_Value],
			        0
			    )
			
			-- 2. Return the decimal value (to be formatted as 0.00% in the UI)
			RETURN
			    varCompliance
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ac175685-3a3d-4aab-bb8e-c1e4e4f7512d

	measure Total_Actual_Value =
			
			-- 1. Calculate the total aggregated sum of all recorded actual values
			-- This will sum every row within the current filter context
			VAR varTotalSum = SUM('results'[Actual_Value])
			
			-- 2. Return the result
			RETURN
			    varTotalSum
		lineageTag: 74b1de12-94d7-4198-a7c5-cb9e69ac5d57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Objective_Actual_Status_Completion_Rate = ```
			
			-- 1. Iterate over the 'kpis' dimension table in the current filter context
			-- AVERAGEX will automatically handle the denominator (e.g., dividing by 3 if there are 3 KPIs)
			VAR varAverageCompletion = 
			    AVERAGEX(
			        'kpis',
			        
			        -- 2. Retrieve the raw compliance percentage for each individual KPI
			        -- COALESCE ensures that if a KPI has no data yet, it counts as 0% rather than being ignored
			        VAR varRawCompliance = COALESCE([Compliance_Actual_Value_Percentage], 0)
			        
			        -- 3. Cap the compliance at 100% (1.0)
			        -- MIN is the most efficient way to cap values in DAX (avoids IF statements)
			        VAR varCappedCompliance = MIN(varRawCompliance, 1)
			        
			        -- 4. Return the capped value to the AVERAGEX iteration loop
			        RETURN
			            varCappedCompliance
			    )
			
			-- 5. Return the final aggregated average (Format this measure as 0.00% in the UI)
			RETURN
			    varAverageCompletion
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5653091a-86fa-41ae-8164-d187acfbbcf8

	measure Dynamic_Compliance = ```
			
			-- 1. Identify the current KPI ID from the visual context
			VAR varCurrentKpi = MAX('kpis'[KPI_ID])
			
			-- 2. Hardcode the routing logic based on specific KPI IDs
			VAR varRoutedCompliance = 
			    SWITCH(
			        TRUE(),
			        -- Cumulative KPIs (Uses Total_Actual_Value)
			        varCurrentKpi IN {7, 9, 10}, [Compliance_Actual_Value_Percentage],
			        
			        -- Snapshot KPIs (Uses Actual_Status)
			        -- Grouped 2, 7, 8, 9, and 10 as they all share the standard Compliance_Percentage logic
			        varCurrentKpi IN {8}, [Compliance_Percentage],
			        
			        -- Default fallback just in case a new KPI is added in the future
			        [Compliance_Percentage] 
			    )
			
			RETURN
			    varRoutedCompliance
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 15fef659-6bb3-468c-9f56-7c65482a31b1

	column Result_ID
		dataType: int64
		formatString: 0
		lineageTag: 7eb8324c-6034-4577-9b50-bbf300eab304
		summarizeBy: count
		sourceColumn: Result_ID

		annotation SummarizationSetBy = Automatic

	column KPI_ID
		dataType: int64
		formatString: 0
		lineageTag: 56f8413a-8610-4945-9887-610cc5c9d7e7
		summarizeBy: none
		sourceColumn: KPI_ID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7bf65e9f-a318-4fbd-9f65-419e37bed182
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Actual_Value
		dataType: double
		lineageTag: 772a0c7d-b421-469c-a358-87297e819ca6
		summarizeBy: sum
		sourceColumn: Actual_Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Is_Beginning_Number
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d08f25ab-8741-49d5-ad71-1192d264e559
		summarizeBy: none
		sourceColumn: Is_Beginning_Number

		annotation SummarizationSetBy = Automatic

	partition Results = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\mauro.turner\Proyectos\Dashboards\Global-IT---OKR-KPI-Dashboard\Datasets\okrs.xlsx"), null, true),
				    Results_Sheet = Origen{[Item="Results",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Results_Sheet, [PromoteAllScalars=true]),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{"Result_ID", "KPI_ID", "Date", "Actual_Value", "Is_Beginning_Number"}),
				    #"Tipo cambiado con configuración regional1" = Table.TransformColumnTypes(#"Otras columnas quitadas", {{"Date", type date}}, "en-US"),
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado con configuración regional1", each ([Result_ID] <> null)),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Filas filtradas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo cambiado con configuración regional" = Table.TransformColumnTypes(#"Filas en blanco eliminadas", {{"Actual_Value", type number}}, "es-AR"),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional",{{"Is_Beginning_Number", type logical}, {"Result_ID", Int64.Type}, {"KPI_ID", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

