table Results
	lineageTag: ffa596c6-aec4-4c63-912a-804618788065

	measure Actual_Status = SUM('results'[Actual_Value])
		formatString: 0
		lineageTag: f92170d1-51f9-4454-9966-172af2ec516a

	measure Calculated_Target_Value = ```
			
			// 1. Identify the unit for the current KPI context
			VAR _UnitName = SELECTEDVALUE(units[Unit_Name])
			
			// 2. Get the raw target value from the KPIs table
			VAR _Target = SELECTEDVALUE(kpis[Target_Value])
			
			// 3. Retrieve the Actual_Value that serves as the baseline (Beginning Number)
			// We use CALCULATE to filter the Results table specifically for the starting point
			VAR _StartingActual = 
			    CALCULATE(
			        MAX(Results[Actual_Value]), 
			        Results[Is_Beginning_Number] = TRUE
			    )
			
			// 4. Final Logic:
			// If Unit is "Percentage", add the Target to the Starting Value.
			// Otherwise, simply return the Target Value.
			RETURN
			IF(
			    _UnitName = "Percentage",
			    _StartingActual + _Target,
			    _Target
			)
			```
		formatString: 0
		lineageTag: a33060ba-5c27-4763-ade5-38bcc11a29f0

	column Result_ID
		dataType: int64
		formatString: 0
		lineageTag: 7eb8324c-6034-4577-9b50-bbf300eab304
		summarizeBy: count
		sourceColumn: Result_ID

		annotation SummarizationSetBy = Automatic

	column KPI_ID
		dataType: int64
		formatString: 0
		lineageTag: 56f8413a-8610-4945-9887-610cc5c9d7e7
		summarizeBy: none
		sourceColumn: KPI_ID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7bf65e9f-a318-4fbd-9f65-419e37bed182
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Actual_Value
		dataType: double
		lineageTag: 772a0c7d-b421-469c-a358-87297e819ca6
		summarizeBy: sum
		sourceColumn: Actual_Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Is_Beginning_Number
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d08f25ab-8741-49d5-ad71-1192d264e559
		summarizeBy: none
		sourceColumn: Is_Beginning_Number

		annotation SummarizationSetBy = Automatic

	partition Results = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\mauro.turner\Proyectos\Dashboards\Global-IT---OKR-KPI-Dashboard\Datasets\okrs.xlsx"), null, true),
				    Results_Sheet = Origen{[Item="Results",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Results_Sheet, [PromoteAllScalars=true]),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{"Result_ID", "KPI_ID", "Date", "Actual_Value", "Is_Beginning_Number"}),
				    #"Tipo cambiado con configuración regional1" = Table.TransformColumnTypes(#"Otras columnas quitadas", {{"Date", type date}}, "en-US"),
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado con configuración regional1", each ([Result_ID] <> null)),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Filas filtradas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo cambiado con configuración regional" = Table.TransformColumnTypes(#"Filas en blanco eliminadas", {{"Actual_Value", type number}}, "es-AR"),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional",{{"Is_Beginning_Number", type logical}, {"Result_ID", Int64.Type}, {"KPI_ID", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

